name: Build and push to GHCR
on:
  push:
    branches: [main]
  pull_request:
jobs:
  build-and-push-to-ghcr-cuda118:
    runs-on: ubuntu-22.04
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 'Login to GitHub Container Registry'
        run: |
          set -xe
          docker login --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }} ghcr.io

      - name: 'Remove cache'
        run: | 
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"

      - name: Build only for PR Cuda 11.7
        if: github.ref != 'refs/heads/main'
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:server"
          file: Dockerfile
          push: false # Do not push image for PR
          cache-from: type=registry,ref=ghcr.io/coqui-ai/xtts-streaming-server:cache-latest; type=registry,ref=ghcr.io/coqui-ai/xtts-streaming-server:cache-pr-${{ github.event.number }}
          cache-to: type=registry,ref=ghcr.io/coqui-ai/xtts-streaming-server:cache-pr-${{ github.event.number }}

      - name: Build and Push image Cuda 11.7
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:server"
          file: Dockerfile
          push: true # Push if merged
          cache-from: type=registry,ref=ghcr.io/coqui-ai/xtts-streaming-server:cache-latest
          cache-to: type=registry,ref=ghcr.io/coqui-ai/xtts-streaming-server:cache-latest
          tags: ghcr.io/coqui-ai/xtts-streaming-server:latest, ghcr.io/coqui-ai/xtts-streaming-server:main-${{ github.sha }}
          #build-args:

  build-and-push-to-ghcr-cuda121:
    runs-on: ubuntu-22.04
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 'Login to GitHub Container Registry'
        run: |
          set -xe
          docker login --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }} ghcr.io

      - name: 'Remove cache'
        run: | 
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"

      - name: Build only for PR cuda 12.1
        if: github.ref != 'refs/heads/main'
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:server"
          file: Dockerfile.cuda121
          push: false # Do not push image for PR
          cache-from: type=registry,ref=ghcr.io/coqui-ai/xtts-streaming-server:cache-latest-cuda121; type=registry,ref=ghcr.io/coqui-ai/xtts-streaming-server:cache-pr-cuda121-${{ github.event.number }}
          cache-to: type=registry,ref=ghcr.io/coqui-ai/xtts-streaming-server:cache-pr-cuda121-${{ github.event.number }}

      - name: Build and Push image cuda 12.1
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:server"
          file: Dockerfile.cuda121
          push: true # Push if merged
          cache-from: type=registry,ref=ghcr.io/coqui-ai/xtts-streaming-server:cache-latest-cuda121
          cache-to: type=registry,ref=ghcr.io/coqui-ai/xtts-streaming-server:cache-latest-cuda121
          tags: ghcr.io/coqui-ai/xtts-streaming-server:latest-cuda121, ghcr.io/coqui-ai/xtts-streaming-server:main-cuda121-${{ github.sha }}
          #build-args:
